networks:
  keycloak:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:15.1.0'
    networks:
      - keycloak
    container_name: keycloak-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak

  keycloak:
    depends_on:
      - postgresql

    image: 'registry1.dso.mil/ironbank/opensource/keycloak/keycloak:20.0.3'

    networks:
      - keycloak
    container_name: keycloak
    ports:
      - '8080:8080'
    command:
      # - "start"
      - "start-dev"
      - "--import-realm"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_DB: "postgres"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_DB_URL_HOST: "postgresql"
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: "keycloak"

      KC_LOG_LEVEL: "org.keycloak.events:DEBUG,org.infinispan:INFO,org.jgroups:INFO"
    volumes:
    - ./my-realm.json:/opt/keycloak/data/import/realm.json
    - ./quarkus.properties:/opt/keycloak/conf/quarkus.properties
    - ./my-demo-keycloak-theme/my-theme:/opt/keycloak/themes/my-theme
